# 2. Input your name, age, and height. Print them using proper data types.
name=input("Enter your name : ")
age=int(input("Enter your age : "))
height=float(input("Enter your height in meter : "))
print(f"hell {name}! ")
print(type(name))
print(f"hi {name} your {age} year old ")
print(type(age))
print(f"And your height is {height} ")
print(type(height))
print("----------------------------------------------------")
